site_name: Django EC IDCard Field
site_author: https://devlance.me/
copyright: <a target="_blank" href="https://devlance.me/">Developed with &hearts; by DEVLANCE</a>


nav:
  - Home: 'index.md'


theme:
  name: material
  font:
      text: Ubuntu 300
      code: Ubuntu mono
  icon:
      logo: fontawesome/solid/tools


markdown_extensions:
  - pymdownx.superfences
  - toc:
      permalink: '#'
